import Link from 'next/link'
import './globals.css'
import { AiOutlineShoppingCart } from 'react-icons/ai'
import Navbar from '@/components/Navbar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}

export default RootLayout